# Project
group = com.github.exopandora.shouldersurfing
javaVersion = 17
javaToolchainVersion = 17
jarName = YesSteveCamera

# Mod options
modVersion = 4.21.0-ysc.0.1.0-test.18
modId = shouldersurfing
modName = YesSteveCamera
modAuthor = DanielFQZ, Exopandora
modContributors = 70CentsApple, Celestia, EchoEllet, EminGT, Estrecka, Farenheith, Fyoncle, mpustovoi, Sabar, TheLegendofSaram, yichifauzi
modDescription = YesSteveCamera adds targeting and animation-driven camera shake to Shoulder Surfing Reloaded. Original camera by Exopandora and Sabar.
modUrl = https://github.com/DanielFQZ/YesSteveCamera

# Forge
forgeCompatibleMinecraftVersions = 1.20,1.20.1

# Fabric
fabricCompatibleMinecraftVersions = 1.20,1.20.1

# Publishing
curseProjectId = 243190
modrinthProjectId = kepjj2sy

# Gradle
org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.parallel = true
